copyright: Copyright © 2022-2023 [HugoMods](https://hugomods.com). All Rights Reserved.
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableRobotsTXT: true

build:
  writeStats: true

taxonomies:
  authors: authors
  tags: tags
  categories: categories
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
  highlight:
    noClasses: false
    lineNos: true
    lineNumbersInTable: false

security:
  funcs:
    getenv:
      - '^HUGO_'
      - '^CI$'
      - '^GITHUB_TOKEN$'