title: HugoMods
defaultContentLanguage: en
enableRobotsTXT: true

outputs:
  home:
    - DecapCMSConfig
    - HTML
    - Offline
    - SearchIndex
    - RSS
    - WebAppManifest

permalinks:
  blog: /blog/:year/:month/:title/
  news: /news/:year/:month/:title/

taxonomies:
  _merge: shallow

markup:
  _merge: deep

build:
  _merge: shallow

menus:
  _merge: deep

security:
  _merge: deep

module:
  imports:
    - path: github.com/hugomods/site/common

baseURL: https://hugomods.com/

languages:
  _merge: deep

  en:
    title: HugoMods
    baseURL: https://hugomods.com/

  zh-hans:
    title: HugoMods
    baseURL: https://zh-hans.hugomods.com/

  zh-hant:
    title: HugoMods
    baseURL: https://zh-hans.hugomods.com/

params:
  hb:
    header:
      main_brand:
    blog:
      sidebar:
        profile:
          company: "[HugoMods](https://github.com/hugomods)"
          location: Internet
          socials:
            github: hugomods
            githubsponsors: https://github.com/sponsors/razonyang
            mastodon: https://techhub.social/@hugomods
            paypal: razonyang
            rss: true
    content_panel:
      repo:
        subpath: home
