- name: _js
  type: boolean
  default: false
  description:
    default: Indicates whether if the chart is written in JavaScript, when `true`, you must `return` the chart options.
    zh-hans: 表示图表是否用 JavaScript 编写的，为 `true` 时，你必须 `return` 图表的参数。
    zh-hant: 表示圖表是否用 JavaScript 編寫的，為 `true` 時，你必須 `return` 圖表的參數。

- name: height
  type: number
  default: 400
  description:
    default: The height of chart container.
    zh-hans: 图表容器高度。
    zh-hant: 圖表容器高度。

- name: weight
  type: number
  default: '100%'
  description:
    default: The width of chart container.
    zh-hans: 图表容器宽度。
    zh-hant: 圖表容器寬度。
